### ISSUE TITLE
Zombie Origin always burns, no matter the time

### ISSUE THREAD

**Issue by SlashJay-8566** [wilyank/soaring_depths#1]
**Describe the bug**
The Zombie Origin Starts To Burn, despite the 

**To Reproduce**
1. Select the Zombie Origin
2. Set Time to Night

**Expected behavior**
The Player should not catch fire.

**Modpack Version: 1.0.0**

**Additional context**
I did not install Optifine. I

**Comment by wilyank** [comment]
Thank you for pointing this out. I believe I know what is going wrong and you can expect a fix within a day

**Comment by wilyank** [comment]
Fixed in commit #8a9b45a
